[package]
name = "zusearch"
version = "0.1.0"
authors = ["Jörn Franke <jornfranke@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# libzusearch must be available to a wide range of different frameworks and applications. 
# This can be only guaranteed at the moment through a cdylib
[lib]
crate-type=["cdylib","rlib"]

[dependencies]
bincode = {version = "1.3.3"}
bloomfilter = {version = "1.0.9"}
chrono = { version = "0.4.19"}
flate2 = { version = "1.0.24"}
#log4rs = { version = "1.0.0"}
log = { version = "0.4.17", features = ["std"] }
regex = { version = "1.5.5"}
rust_decimal = { version = "1.25.0"}
serde = {version="1.0.138", features = ["derive"] }
serde_yaml = {version = "0.8.24"}
thiserror = {version = "1.0.31"}
tokio = { version = "1.19.2"}
wasm-bindgen = { version = "0.2.81"}