[package]
name = "zusearch"
version = "0.1.0"
authors = ["Jörn Franke <jornfranke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# libzusearch must be available to a wide range of different frameworks and applications. 
# This can be only guaranteed at the moment through a cdylib
# Modules for libzusearch should be ideally written in Rust through the dylib - although it does not provide a stable ABI yet.
[lib]
crate-type=["dylib","rlib"]

[dependencies]
bloomfilter = {version = "1.0.5"}
chrono = { version = "0.4.19"}
dlopen = { version = "0.1.8"}
flate2 = { version = "1.0"}
log4rs = { version = "1.0.0"}
log = { version = "0.4.0", features = ["std"] }
regex = { version = "1.5.4"}
rust_decimal = { version = "1.14.1"}
serde = {version="1.0.126"}
serde_yaml = {version = "0.8.17"}
thiserror = {version = "1.0.26"}
tokio = { version = "1.6.0"}
