name: zusearch-build
on: [push]
env:
    RUST_VERSION: "1.62"
    RUSTUP_HOME: "./rust/rustup"
    CARGO_HOME: "./rust/cargo"

jobs:
  build-zusearch-lib:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
        submodules: recursive
     - name: Cache Rust
       id: cache-rust
       uses: actions/cache@v3
       with:
        path: rust
        key: ${{ runner.os }}-rust-${{env.RUST_VERSION}}
     - name: Install rust
       if: steps.cache-rust.outputs.cache-hit != 'true'
       run: |
              mkdir -p $RUSTUP_HOME
              mkdir -p §CAROGO_HOME
              curl https://sh.rustup.rs -sSf | sh -s -- -y
              rustup install $RUST_VERSION
              rustup target add wasm32-wasi
              rustup target add wasm32-unknown-unknown
     - name: Display version
       run: |
           rustc --version
           cargo --version
